CREATE TABLE USER(
	  USER_ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
	  FIRST_NAME varchar(255) DEFAULT NULL,
	  LAST_NAME varchar(255) DEFAULT NULL,
	  USERNAME varchar(255) DEFAULT NULL,
	  IS_ACTIVE tinyint(1) DEFAULT NULL,
      PRIMARY KEY (USER_ID)
	);
